### ISSUE TITLE
While using the create mod, it is impossible to move the wireless modem in any of the existing ways

### ISSUE THREAD

**Issue by AlastorCrowley227** [SquidDev-CC/CC-Tweaked#1913]
### Minecraft Version

1.20.1

### Version

1.111.0

### Details

I wanted to move the computer with an ender modem using gantry carriage, but it didn't work out. As I found out later, the wireless modem cannot be moved at all, including the usual piston.

**Comment by SquidDev** [comment]
Hi, thanks for the report! This is very odd, this should have been resolved with #948. I've just tested this (Create 0.5.1.f, Forge 47.1.0) and this appears to work and move the computer+modem as expected:

![A CC computer with a modem to the right above it (both superglued together), on top of a Create gantry.](https://github.com/user-attachments/assets/b0055ca7-693e-46ac-b23d-5d0fbf40feb9)

Just to confirm, is the modem part of the superglued structure?

**Comment by AlastorCrowley227** [comment]
He doesn't want to superglue to the structure. Also, I can't move it separately by itself.
![javaw_vNfmzKgEqV](https://github.com/user-attachments/assets/23bcd8ed-ee0d-4053-b2b2-b6551052f2f3)

Update: I just tried to glue it together, as you did, and I managed to move it, but I still can't move it separately or glue it to the structure itself (meaning glue the block separately, and not make it part of the superglue area).
